package com.seleniumtests.connectors.bugtracker;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.filefilter.FileFilterUtils;
import org.apache.commons.io.filefilter.IOFileFilter;
import org.apache.log4j.Logger;

import com.seleniumtests.connectors.bugtracker.jira.JiraBean;
import com.seleniumtests.connectors.bugtracker.jira.JiraConnector;
import com.seleniumtests.core.SeleniumTestsContextManager;
import com.seleniumtests.customexception.ConfigurationException;
import com.seleniumtests.driver.screenshots.ScreenShot;
import com.seleniumtests.reporter.logger.TestStep;
import com.seleniumtests.util.FileUtility;
import com.seleniumtests.util.logging.SeleniumRobotLogger;

public abstract class BugTracker {

	public static final String STEP_KO_PATTERN = "Step %d KO\n\n";
	protected static Logger logger = SeleniumRobotLogger.getLogger(BugTracker.class);

	/**
	 * Create an issue object
	 * @param assignee		assignee to which this issue will be sent. May be null
	 * @param priority		priority of the new issue. May be null
	 * @param issueType		Type of the issue to create. May be null
	 * @param reporter		person who reported the issue. May be null
	 * @param customFields	custom information to add to issue. They must be supported by bugtracker
	 * @param components	components to which this issue belong. Depends on bugtracker
	 * @param application	the tested application
	 * @param environment	the environment where we tested
	 * @param testNgName	name of the TestNG test. Helps to build the summary
	 * @param testName		method name (name of scenario)
	 * @param description	Description of the test. May be null
	 * @param testSteps		Test steps of the scenario
	 * @return
	 */
	public IssueBean createIssueBean(String assignee, 
			String priority, 
			String issueType,
			String reporter,
			Map<String, String> customFields, 
			List<String> components,
			String application,
			String environment,
			String testNgName,
			String testName,
			String description,
			List<TestStep> testSteps) {
		

		List<ScreenShot> screenShots = new ArrayList<>();
		StringBuilder fullDescription = new StringBuilder(description);
		int stepIdx = 0;
		boolean found = false;
		for (TestStep testStep: testSteps) {
			if (testStep.getName().startsWith("Test end")) {
				
				fullDescription.append(String.format(STEP_KO_PATTERN, stepIdx));

				fullDescription.append(String.format("Step '%s' in error\n\n", testSteps.get(stepIdx - 1).getName()));
				fullDescription.append(testStep.toString() + "\n\n");
				screenShots = testStep.getSnapshots().stream()
										.map(s -> s.getScreenshot())
										.collect(Collectors.toList());
				found = true;
				break;
			}
			stepIdx += 1;
		}

		// don't create issue if test has not been executed
		if (stepIdx == 0 || !found) {
			return null;
		}

		fullDescription.append("For more details, see attached .zip file");
		String summary = String.format("[Selenium][%s][%s][%s] test %s KO", application, environment, testNgName, testName);

		// get HTML report generated by SeleniumTestsReporter2 class
		File zipFile = null;
		Path outRoot = null;
		try {
			File resourcesFolder = Paths.get(SeleniumTestsContextManager.getGlobalContext().getOutputDirectory(), "resources").toFile().getAbsoluteFile();
			File testResultFolder = Paths.get(SeleniumTestsContextManager.getGlobalContext().getOutputDirectory(), testName).toFile().getAbsoluteFile();
			outRoot = Files.createTempDirectory("result");
			Path tempResourcesFolder = Files.createDirectory(Paths.get(outRoot.toString(), "resources"));
			Path tempResultFolder = Files.createDirectory(Paths.get(outRoot.toString(), testName));

			IOFileFilter aviFiles = FileFilterUtils.notFileFilter(
					FileFilterUtils.or(
							FileFilterUtils.suffixFileFilter(".avi", null), // exclude video
							FileFilterUtils.suffixFileFilter(".zip", null)  // exclude previous reports
					)
			);

			// copy test results
			FileUtils.copyDirectory(testResultFolder, tempResultFolder.toFile(), aviFiles);

			// copy resources
			try {
				FileUtils.copyDirectory(resourcesFolder, tempResourcesFolder.toFile(), aviFiles);
			} catch (IOException e) {}

			// create zip
			zipFile = File.createTempFile("result", ".zip");
			zipFile.deleteOnExit();
			FileUtility.zipFolder(outRoot.toFile(), zipFile);
		} catch (IOException e) {
		} finally {
			if (outRoot != null) {
				try {
					FileUtils.deleteDirectory(outRoot.toFile());
				} catch (IOException e) {}
			}
		}

		if (this instanceof JiraConnector) {
			return new JiraBean(summary,
					fullDescription.toString(),
					priority,
					issueType,
					testName,
					testSteps.get(stepIdx),
					assignee,
					reporter,
					screenShots,
					zipFile,
					customFields,
					components);
		} else {
			return new IssueBean(summary,
				fullDescription.toString(),
				priority,
				testName,
				testSteps.get(stepIdx),
				assignee,
				reporter,
				screenShots,
				zipFile,
				customFields);
		}
	}
	
	/**
	 * Creates an issue if it does not already exist
	 * First we search for a similar open issue (same summary)
	 * If it exists, then we check the step where we failed. If it's the same, we do nothing, else, we update the issue, saying we failed on an other step.
	 * @param assignee		assignee to which this issue will be sent. May be null
	 * @param priority		priority of the new issue. May be null
	 * @param issueType		Type of the issue to create. May be null
	 * @param reporter		person who reported the issue. May be null
	 * @param customFields	custom information to add to issue. They must be supported by bugtracker
	 * @param components	components to which this issue belong. Depends on bugtracker
	 * @param application	the tested application
	 * @param environment	the environment where we tested
	 * @param testNgName	name of the TestNG test. Helps to build the summary
	 * @param testName		method name (name of scenario)
	 * @param description	Description of the test. May be null
	 * @param testSteps		Test steps of the scenario
	 */
	public void createIssue(
			String assignee, 
			String priority,
			String issueType,
			String reporter,
			Map<String, String> customFields, 
			List<String> components,
			String application,
			String environment,
			String testNgName,
			String testName,
			String description,
			List<TestStep> testSteps) {

		IssueBean issueBean = createIssueBean(assignee, priority, issueType, reporter, customFields, components, application, environment, testNgName, testName, description, testSteps);
		if (issueBean == null) {
			return;
		}
		
		// get index of the last step to know where we failed
		int stepIdx = 0;
		for (TestStep testStep: testSteps) {
			if (testStep.getName().startsWith("Test end")) {
				break;
			}
			stepIdx += 1;
		}
		
		// check that a Jira does not already exist for the same test / appication / version. Else, complete it if the step is error is not the same
		IssueBean currentIssue = issueAlreadyExists(issueBean);
		if (currentIssue != null) {
			if (currentIssue.getDescription().contains(String.format(STEP_KO_PATTERN, stepIdx))) {
				logger.info(String.format("Jira %s already exists", currentIssue.getId()));
			} else {
				updateIssue(currentIssue.getId(), "Scenario fails on another step " + issueBean.getTestStep().getName(), issueBean.getScreenShots());
			}
		} else {
			createIssue(issueBean);
		}
	}
	
	  /**
     * Check if issue already exists, and if so, returns an updated IssueBean
     *
     * @return
     */
	public abstract IssueBean issueAlreadyExists(IssueBean issue);
	
	/**
	 * Update an existing issue with a new message and new screenshots.
	 * Used when an issue has already been raised, we complete it
	 * @param issueId			Id of the issue
	 * @param messageUpdate		message to add to description
	 * @param screenShots		New screenshots
	 */
	public abstract void updateIssue(String issueId, String messageUpdate, List<ScreenShot> screenShots);
	
	/**
	 * Create an issue
	 * @param issueBean
	 * @return
	 */
	public abstract void createIssue(IssueBean issueBean);
	
	/**
     * Close issue
     * @param issueId           ID of the issue
     * @param closingMessage    Message of closing
     */
    public abstract void closeIssue(String issueId, String closingMessage);

	public static BugTracker getInstance(String type, String url, String project, String user, String password) {

		if ("jira".equals(type)) {
			return new JiraConnector(url, project, user, password);
		} else if ("fake".equals(type)) {
			return new FakeBugTracker();
		} else {
			throw new ConfigurationException(String.format("BugTracker type [%s] is unknown, valid values are: ['jira']", type));
		}
	}
}
