package com.seleniumtests.browserfactory;

import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

import com.seleniumtests.customexception.ConfigurationException;
import com.seleniumtests.driver.BrowserType;
import com.seleniumtests.util.logging.SeleniumRobotLogger;
import com.seleniumtests.util.osutility.OSUtility;
import com.seleniumtests.util.osutility.OSUtilityFactory;

public class BrowserInfo {
	
	private static final Logger logger = SeleniumRobotLogger.getLogger(BrowserInfo.class);

	private static final Pattern REG_CHROME_VERSION = Pattern.compile(".*chrome-(\\d+)-(\\d+).*");
	private static final Pattern REG_ANDROID_VERSION = Pattern.compile(".*android-(\\d+\\.\\d+).*");
	private static List<String> driverList;
	
	private String version;
	private String path;
	private String driverFileName;
	private String os;
	private BrowserType browser;
	private boolean driverFileSearched = false;
	
	/**
	 * Create information about the 
	 * @param browser
	 * @param version
	 * @param path				path to browser executable
	 * @param driverFileName
	 */
	public BrowserInfo(BrowserType browser, String version, String path) {
		this.browser = browser;
		this.path = path;
		this.version = version;
		os = OSUtility.getCurrentPlatorm().toString().toLowerCase();
		if (os.equals("linux")) {
			os = "unix";
		}
	}
	
	public BrowserInfo getEmptyBrowserInfo() {
		BrowserInfo info = new BrowserInfo(BrowserType.NONE, "", null);
		info.driverFileSearched = true;
		info.driverFileName = null;
		return info;
	}

	private void addDriverFile() throws IOException {
		switch (browser) {
			case CHROME:
				addChromeDriverFile();
				break;
			case BROWSER:
				addAndroidDriverFile();
				break;
			case FIREFOX:
				addFirefoxDriverFile();
				break;
			case EDGE:
				addEdgeDriverFile();
				break;
			case INTERNET_EXPLORER:
				addInternetExplorerDriverFile();
				break;
			default:
				driverFileName = null;
		}
		checkResourceExists();
	}
	
	private void checkResourceExists() {
		if (driverFileName != null && getClass().getClassLoader()
				.getResourceAsStream(String.format("drivers/%s/%s%s", os, driverFileName, OSUtilityFactory.getInstance().getProgramExtension())) == null) {
			throw new ConfigurationException(String.format("Driver file %s does not exist in resources", driverFileName));
		}
	}
	
	public List<String> getDriverFiles() throws IOException {
		if (driverList != null) {
			return driverList;
		} else {
			// try to get file names from list generated by maven. In IDE mode, this should not work and we fall back to resource reading
			try {
				List<String> drivers = new ArrayList<>();
				
				String[] driverListFromFile = IOUtils.readLines(BrowserInfo.class.getClassLoader().getResourceAsStream("driver-list.txt"), Charset.forName("UTF-8")).get(0).split(",");
	
				logger.info("getting drivers from driver-list.txt");
		    	for (String driverNameWithPf: driverListFromFile) {
		    		if (!driverNameWithPf.startsWith(os)) {
		    			continue;
		    		}
		    		String driverName = driverNameWithPf.replace(os + "/", "");
		    		drivers.add(driverName);
		        }
		    	return drivers;
			} catch (NullPointerException | IOException e) {
				logger.info("getting drivers from resources");
				return IOUtils.readLines(getClass().getClassLoader().getResourceAsStream(String.format("drivers/%s/", os)), Charset.forName("UTF-8"));
			}
		}
	}
	
	/**
	 * Find the most suitable driver when using chrome browser
	 * @throws IOException
	 */
	private void addChromeDriverFile() throws IOException {
		List<String> driverFiles = getDriverFiles();
		driverFiles = driverFiles.stream()
				.filter(s -> s.contains("chrome-") && s.startsWith("chromedriver_"))
				.map(s -> s.replace(".exe", ""))
				.sorted()
				.collect(Collectors.toList());

		if (driverFiles.isEmpty()) {
			throw new ConfigurationException("no chromedriver in resources");
		}
		
		Map<Integer, String> driverVersion = new HashMap<>();
		
		for (String fileName: driverFiles) {
			Matcher matcher = REG_CHROME_VERSION.matcher(fileName);
			if (matcher.matches()) {
				int minVersion = Integer.parseInt(matcher.group(1));
				int maxVersion = Integer.parseInt(matcher.group(2));
				if (maxVersion < minVersion) {
					throw new ConfigurationException(String.format("Chrome driver file %s version is incorrect, max version should be > to min version", fileName));
				} else {
					for (int i = minVersion; i <= maxVersion; i++) {
						driverVersion.put(i, fileName);
					}
				}
			} else {
				throw new ConfigurationException(String.format("Driver %s is excluded as it does not match the pattern 'chromedriver_<version>_chrome-<minVersion>-<maxVersion>'", fileName));
			}
		}
		
		int chromeVersion = Integer.parseInt(version.split("\\.")[0]);
		driverFileName = driverVersion.get(chromeVersion);
		
		// when chrome version is greater than driver version, take the last driver and display warning as something may go wrong
		if (driverFileName == null && chromeVersion > Collections.max(driverVersion.keySet())) {
			driverFileName = driverFiles.get(driverFiles.size() - 1);
			
			logger.warn("--------------------------------------------------------------------");
			logger.warn(String.format("Chrome version %d does not have any associated driver, update seleniumRobot version, the latest driver has been used", chromeVersion));
			logger.warn("--------------------------------------------------------------------");
		} else if (driverFileName == null) {
			throw new ConfigurationException(String.format("Chrome version %d does not have any associated driver, update seleniumRobot version", chromeVersion));
		}
	}
	
	/**
	 * Add the most suitable chrome driver for android driver version
	 * @throws IOException 
	 */
	private void addAndroidDriverFile() throws IOException {
		List<String> driverFiles = getDriverFiles();
		driverFiles = driverFiles.stream()
								.filter(s -> s.contains("android-") && s.startsWith("chromedriver_"))
								.map(s -> s.replace(".exe", ""))
								.sorted()
								.collect(Collectors.toList());
		
		if (driverFiles.isEmpty()) {
			throw new ConfigurationException("no chromedriver in resources");
		}
		
		Map<String, String> driverVersion = new HashMap<>();
		
		for (String fileName: driverFiles) {
			Matcher matcher = REG_ANDROID_VERSION.matcher(fileName);
			if (matcher.matches()) {
				driverVersion.put(matcher.group(1), fileName);

			} else {
				throw new ConfigurationException(String.format("Driver %s is excluded as it does not match the pattern 'chromedriver_<version>_android-<x.y>'", fileName));
			}
		}
		
		driverFileName = driverVersion.get(version);
		
		if (driverFileName == null) {
			throw new ConfigurationException(String.format("Chrome version %s does not have any associated driver, update seleniumRobot version", version));
		}
	}
	
	/**
     * use firefox if version is below 47
     * @param versionString
     * @return
     */
    public static boolean useLegacyFirefoxVersion(String versionString) {
    	Pattern regMozilla = Pattern.compile(".*?(\\d+)\\..*");
    	Matcher versionMatcher = regMozilla.matcher(versionString);
		if (versionMatcher.matches()) {
			String version = versionMatcher.group(1);
			if (Integer.parseInt(version) < 48) {
				return true;
			}
		} 
		return false;
    }
	
	private void addFirefoxDriverFile() {
		if (!useLegacyFirefoxVersion(version)) {
			driverFileName = "geckodriver";
		}
	}
	
	/**
	 * Edge driver depends on windows build
	 */
	private void addEdgeDriverFile() {
		driverFileName = "MicrosoftWebDriver_" + version;
	}
	
	/**
	 * IE driver version depends on IE version itself
	 */
	private void addInternetExplorerDriverFile() {
		if (Integer.parseInt(version) < 10) {
			driverFileName = "IEDriverServer_x64";
    	} else {
    		driverFileName = "IEDriverServer_Win32";
    	}
		
	}
	
	public String getVersion() {
		return version;
	}
	public String getPath() {
		return path;
	}

	public BrowserType getBrowser() {
		return browser;
	}

	public String getDriverFileName() {
		if (!driverFileSearched) {
			try {
				addDriverFile();
			} catch (IOException e) {
				logger.error("Cannot get driver file", e);
			} finally {
				driverFileSearched = true;
			}
		}
		return driverFileName;
	}
	
	/**
	 * For test only
	 * @param driverFileName
	 */
	public void setDriverFileName(String driverFileName) {
		this.driverFileName = driverFileName;
		driverFileSearched = true;
	}

	public static List<String> getDriverList() {
		return driverList;
	}

	public static void setDriverList(List<String> driverList) {
		BrowserInfo.driverList = driverList;
	}
	
	/**
	 * get 
	 * @return
	 */
    public List<Integer> getProgramPid(String programName, List<Integer> existingPids) {
    	final String jvmName = ManagementFactory.getRuntimeMXBean().getName();
        final int index = jvmName.indexOf('@');
        
        OSUtility osUtility = OSUtilityFactory.getInstance();
        
        if(index == 0) {
        	return new ArrayList<>();
        }
        try {
            String processId = Long.toString(Long.parseLong(jvmName.substring(0, index)));
            List<Integer> driverProcesses = osUtility.getChildProcessPid(Integer.parseInt(processId), programName + osUtility.getProgramExtension(), existingPids);
            return driverProcesses;
        } catch (Exception e) {
        	logger.warn("could not get driver pid", e);
        	return new ArrayList<>();
        }
    }
    
    /**
     * Returns the list of pids for existing drivers and browsers. These are direct programes launched by seleniumRobot
     * @param existingPids
     * @return
     */
    public List<Integer> getDriverAndBrowserPid(List<Integer> existingPids) {
    	
    	List<Integer> pids = new ArrayList<>();
    	
    	// no driver used to connect to browser
    	if ((browser == BrowserType.FIREFOX && driverFileName == null) || browser == BrowserType.SAFARI) {
    		pids.addAll(getBrowserPid(existingPids));
    	} else {
    		pids.addAll(getDriverPid(existingPids));
    	}
    	
    	return pids;
    }
    
    /**
     * Get the driver process created by selenium. 
     * @param existingPids
     * @return
     */
    public List<Integer> getDriverPid(List<Integer> existingPids) {
    	return getProgramPid(driverFileName, existingPids);
    }
    
    public List<Integer> getBrowserPid(List<Integer> existingPids) {
    	return getProgramPid(browser.getBrowserType().substring(1) + OSUtilityFactory.getInstance().getProgramExtension(), existingPids);
    }
    
    /**
     * Get the list of pids for the browser launched by driver and all subprocess created by browser
     * @param driverPid
     * @return
     */
    public List<Integer> getAllBrowserSubprocessPids(List<Integer> driverPids) {
    	OSUtility osUtility = OSUtilityFactory.getInstance();
    	List<Integer> allPids = new ArrayList<>();
    	
    	try {
    		for (Integer driverPid: driverPids) {
    			List<Integer> browserPids = osUtility.getChildProcessPid(driverPid, null, new ArrayList<>());
    			allPids.addAll(browserPids);
    			for (Integer pid: browserPids) {
    				List<Integer> subBrowserPids = osUtility.getChildProcessPid(driverPid, null, new ArrayList<>());
    				allPids.addAll(browserPids);
    			}
    		}
    		return allPids;
    		
    		
		} catch (IOException e) {
			return new ArrayList<>();
		}
    }

}
